---
# https://pre-commit.com/
- name: Install pre-commit
  pip:
    name: pre-commit
    state: present
    executable: "{{ ansible_env.HOME }}/.local/python/bin/pip"

- name: user.name for git config
  become_user: "{{ username }}"
  git_config:
    name: user.name
    scope: global
    value: "{{ gitusername }}"

- name: user.email for git config
  become_user: "{{ username }}"
  git_config:
    name: user.email
    scope: global
    value: "{{ email }}"

- name: Set git to use SSH for GitHub
  git_config:
    name: "url.ssh://git@github.com/.insteadOf"
    value: "https://github.com/"
    scope: global

- name: Set git to use SSH for GitLab
  git_config:
    name: "url.ssh://git@gitlab.com/.insteadOf"
    value: "https://gitlab.com/"
    scope: global

- name: Sign tags with ssh
  git_config:
    name: "tag.gpgSign"
    value: "true"
    scope: global

- name: Sign commits with ssh
  git_config:
    name: "gpg.format"
    value: "ssh"
    scope: global

- name: Set allowed signers allowed
  git_config:
    name: "gpg.ssh.allowedSigners"
    value: "~/.ssh/allowed_signers"
    scope: global

- name: Set signingkey
  git_config:
    name: "user.signingKey"
    value: "~/.ssh/id_ed25519_sk_rk"
    scope: global
