---
# https://pre-commit.com/
- name: Install pre-commit
  ansible.builtin.pip:
    name: pre-commit
    state: present
    executable: "{{ ansible_facts['env']['HOME'] }}/.local/python/bin/pip"

- name: Read current global git config values
  ansible.builtin.command:
    argv:
      - git
      - config
      - --global
      - --get
      - "{{ item.name }}"
  loop:
    - name: user.name
      value: "{{ dev_gitusername }}"
    - name: user.email
      value: "{{ dev_email }}"
    - name: "url.ssh://git@github.com/.insteadOf"
      value: "https://github.com/"
    - name: "url.ssh://git@gitlab.com/.insteadOf"
      value: "https://gitlab.com/"
    - name: tag.gpgSign
      value: "true"
    - name: gpg.format
      value: "ssh"
    - name: gpg.ssh.allowedSignersFile
      value: "~/.ssh/allowed_signers"
    - name: user.signingKey
      value: "~/.ssh/id_ed25519_sk_rk_yubikey_no_touch"
    - name: commit.gpgSign
      value: "true"
    - name: init.defaultBranch
      value: "main"
  register: git_config_current
  changed_when: false
  failed_when: false

- name: Set differing global git config values
  ansible.builtin.command:
    argv:
      - git
      - config
      - --global
      - --replace-all
      - "{{ item.item.name }}"
      - "{{ item.item.value }}"
  loop: "{{ git_config_current.results }}"
  loop_control:
    label: "{{ item.item.name }}"
  when: item.rc != 0 or item.stdout != item.item.value
