---
- name: Enable sudo without password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: "{{ dev_username }} ALL=(ALL) NOPASSWD: ALL"
    state: present
    validate: 'visudo -cf %s'

# Set some custom facts

- name: Set effective group for Linux machines
  ansible.builtin.set_fact:
    effective_group: "{{ dev_group }}"
  when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"

- name: Set effective group for macOS machines
  ansible.builtin.set_fact:
    effective_group: "{{ dev_macos_group }}"
  when: ansible_os_family == "Darwin"

# Make common directories

- name: Make .local/bin directory
  ansible.builtin.file:
    path: "~/.local/bin"
    state: directory
    owner: "{{ dev_username }}"
    group: "{{ effective_group }}"
    mode: '750'

- name: Create .config directory
  ansible.builtin.file:
    path: "~/.config"
    state: directory
    owner: "{{ dev_username }}"
    group: "{{ effective_group }}"
    mode: '750'

# # Include required collections
#     #
# # Work around circular dependency
# - name: Install community.general collection workaround
#   command: ansible-galaxy collection install community.general
#
# - name: Install collections
#   ansible.builtin.include_tasks: tasks/collections.yml

#  OS specific tasks

- name: Debian specific tasks
  ansible.builtin.include_tasks: tasks/debian.yml
  when: ansible_os_family == "Debian"

- name: RedHat specific tasks
  ansible.builtin.include_tasks: tasks/redhat.yml
  when: ansible_os_family == "RedHat"

- name: MacOS specific tasks
  ansible.builtin.include_tasks: tasks/macos.yml
  when: ansible_os_family == "Darwin"

- name: Install luacheck
  ansible.builtin.shell:
    cmd: luarocks install luacheck --local
  # LUA EPEL luarocks is poked
  when: ansible_os_family != "RedHat"
  changed_when: false

# Tasks that are common to all OSes

- name: Configure and install zsh
  ansible.builtin.include_tasks: zsh.yml

- name: Configure and install tmux
  ansible.builtin.include_tasks: tmux.yml

- name: Configure and install ssh
  ansible.builtin.include_tasks: ssh.yml

- name: Install golang
  ansible.builtin.include_tasks: golang.yml

- name: Install  rust
  ansible.builtin.include_tasks: rust.yml

- name: Install npm
  ansible.builtin.include_tasks: npm.yml

- name: Install python
  ansible.builtin.include_tasks: python.yml

- name: Install terraform
  ansible.builtin.include_tasks: terraform.yml

- name: Install and configure neovim
  ansible.builtin.include_tasks: neovim.yml

- name: Install vale
  ansible.builtin.include_tasks: vale.yml

- name: Install hugo
  ansible.builtin.include_tasks: hugo.yml

- name: Install kubernetes tools
  ansible.builtin.include_tasks: kubernetes.yml

- name: Install yubikey and solo key tools
  ansible.builtin.include_tasks: yubikey.yml

# Add git last as we mangle the git config to force ssh
- name: Configure git
  ansible.builtin.include_tasks: git.yml
