---
- name: Remove old n
  ansible.builtin.file:
    path: ~/.local/n
    state: absent

- name: Download n-install script
  ansible.builtin.get_url:
    url: https://bit.ly/n-install
    dest: /tmp/n-install
    mode: 0750

- name: Run n-install script
  ansible.builtin.command: bash /tmp/n-install -y
  environment:
    N_PREFIX: "{{ ansible_env.HOME }}/.local/n"

- name: Create npm package directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/npm"
    state: directory
    mode: 0750

- name: Set npm prefix
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.npmrc"
    line: prefix={{ ansible_env.HOME }}/.local/npm
    create: true
    state: present
    mode: 0640
