---
- name: Install epel
  become: true
  ansible.builtin.dnf:
    name: "epel-release"
    state: present

- name: Enable crb repository
  become: true
  ansible.builtin.command: dnf config-manager --set-enabled crb
  changed_when: false
  failed_when: false

- name: Install packages on Red Hat-based systems
  become: true
  ansible.builtin.dnf:
    name: "{{ dev_common_packages + dev_redhat_packages }}"
    state: present
