- name: Install epel
  yum:
    name: "epel-release"
    state: present
  become: yes

- name: Install packages on Red Hat-based systems
  yum:
    name: "{{ common_packages + redhat_packages }}"
    state: present
  become: yes
