---
- name: Remove old rust
  ansible.builtin.file:
    path: ~/.cargo
    state: absent

- name: Download rust install script
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: 0750

- name: Run rust install script
  ansible.builtin.command: bash /tmp/sh.rustup.rs -y
