---
- name: "Create .ssh"
  file:
    path: "~/.ssh"
    state: directory
    mode: '0755'

- name: generate SSH key "id_rsa"
  community.crypto.openssh_keypair:
    path: "~/.ssh/id_rsa"
    type: rsa
    size: 4096
    state: present
    force: no
