---
- name: Link zshrc
  ansible.builtin.file:
    src: "~/personal/dotfiles/tmux.conf"
    dest: "~/.tmux.conf"
    owner: "{{ dev_username }}"
    group: "{{ effective_group }}"
    state: link

- name: Clone tpm
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "~/.tmux/plugins/tpm"
    update: true
    depth: 1

- name: Install tmux plugins
  ansible.builtin.shell: "~/.tmux/plugins/tpm/scripts/install_plugins.sh"
