---
- name: Remove old versions of yubico-piv-tool
  become: true
  ansible.builtin.file:
    path: "/tmp/yubico-piv-tool"
    state: absent

- name: Clone yubico-piv-tool
  ansible.builtin.git:
    repo: https://github.com/Yubico/yubico-piv-tool.git
    dest: "/tmp/yubico-piv-tool"
    depth: 1

- name: Make build directory
  ansible.builtin.file:
    path: "/tmp/yubico-piv-tool/build"
    state: directory
    mode: 0755

- name: Run cmake yubico-piv-tool
  ansible.builtin.command: cmake ..
  args:
    chdir: "/tmp/yubico-piv-tool/build"

- name: Run make yubico-piv-tool
  ansible.builtin.command: make
  args:
    chdir: "/tmp/yubico-piv-tool/build"

- name: Install yubico-piv-tool
  ansible.builtin.command: make install
  args:
    chdir: "/tmp/yubico-piv-tool/build"
  become: true

- name: Install solokey packages
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
    executable: "{{ ansible_env.HOME }}/.local/python/bin/pip"
  with_items:
    - "solo1"
    - "fido2==0.9.3"
