---
- name: Install hugo
  command: "{{ ansible_env.HOME }}/.local/go/bin/go install -tags extended github.com/gohugoio/hugo@latest"
  environment:
    CGO_ENABLED: "1"
  args:
    creates: "{{ ansible_env.HOME }}/.local/go/bin/hugo"
