---
- name: Get the vale versions information
  uri:
    url: https://api.github.com/repos/errata-ai/vale/releases/latest
    method: GET
    return_content: yes
    headers:
      Accept: application/vnd.github.v3+json
  register: vale_versions_response
  failed_when: vale_versions_response.status != 200

- name: Set the latest stable vale version as a fact
  set_fact:
    vale_version: "{{ vale_versions_response.json.tag_name }}"

- name: Download vale
  vars:
    arch_map:
      x86_64: "64-bit"
      arm64: "arm64"
  get_url:
    url: "https://github.com/errata-ai/vale/releases/download/{{ vale_version }}/vale_{{ vale_version | regex_replace('^v', '') }}_Linux_{{ arch_map[ansible_architecture] }}.tar.gz"
    dest: "/tmp"
    mode: 0644

- name: Extract vale
  vars:
    arch_map:
      x86_64: "64-bit"
      arm64: "arm64"
  unarchive:
    src: "/tmp/vale_{{ vale_version | regex_replace('^v', '') }}_Linux_{{ arch_map[ansible_architecture] }}.tar.gz"
    dest: "~/.local/bin"
    remote_src: yes
