---
- name: Install github cli task
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    ansible_python_interpreter: >-
      {{
        '/usr/bin/python3'
        if lookup('ansible.builtin.fileglob', '/usr/bin/python3', errors='ignore')
        else ansible_playbook_python
      }}

  tasks:
    - name: Run only github cli tasks from the dev role
      ansible.builtin.include_role:
        name: dev
        tasks_from: github_cli
